### PR TITLE
SSL Check and Kind 3 Management

### LINKED ISSUE #189: Implement signing in to see own favourite relays
**Is your feature request related to a problem? Please describe.**
Please implement window.nostr to sign in, and once signed in, show relays from one's self `kind 3` event `content` field.

**Describe the solution you'd like**
1. Allow signing in using a Nostr extension: Alby, nos2x, Blockcore Wallet.
2. Once signed in, fetch the `kind 3` event from the user's pubkey.
3. Show relays selected as pinned/favourite.

**Describe alternatives you've considered**
None

**Additional context**
None

### LINKED ISSUE #216: Show link to SSLLabs for relays
**Describe the solution you'd like**
Show the SSLLabs link on the relay profile page so that relay operators can detect if their SSL is setup correctly.
Example: https://www.ssllabs.com/ssltest/analyze.html?d=nostr-relay.wlvs.space

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by dskvr**
Also some other stuff you might wanna check out 

Resolves #216 
Resolves #189 

Screen Shot 2023-01-17 at 1 27 13 AM
Screen Shot 2023-01-17 at 1 27 16 AM

Screen Shot 2023-01-17 at 1 27 26 AM

### CODE REVIEW

**Comment by Cameri** [comment]
Woah! Amazing!

**Comment by dskvr** [comment]
@Cameri Read to ship?

**Comment by Cameri** [comment]
> @Cameri Ready to ship? Made some updates

Looks solid to me!

**Comment by dskvr** [comment]
Polished, ready for staging

**Comment by dskvr** [comment]
Can't merge into production until I've dealt with #215

**Pull request merged**
